### ISSUE TITLE
Can't run on mac

### ISSUE THREAD

**Issue by riderx** [ebidel/lighthouse-ci#26]
lh work on our ci but not on our mac
```
> angul@0.0.0 lh /Users/martindonadieu/Projects/angular-well-config
> lighthouse-ci "/home/travis/build/WildCodeSchool/laloupe-0218-mastermin"

Using runner: chrome
/Users/martindonadieu/Projects/angular-well-config/node_modules/lighthouse-ci/runlighthouse.js:106
    owner: repoSlug.split('/')[0],
                    ^

TypeError: Cannot read property 'split' of undefined
    at getConfig (/Users/martindonadieu/Projects/angular-well-config/node_modules/lighthouse-ci/runlighthouse.js:106:21)
    at Object.<anonymous> (/Users/martindonadieu/Projects/angular-well-config/node_modules/lighthouse-ci/runlighthouse.js:150:16)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angul@0.0.0 lh: `lighthouse-ci "/home/travis/build/WildCodeSchool/laloupe-0218-mastermin"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angul@0.0.0 lh script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/martindonadieu/.npm/_logs/2018-03-29T12_10_44_403Z-debug.log
```

**Comment by ebidel** [comment]
runLighthouse.js is only intended to work on Travis atm. https://github.com/ebidel/lighthouse-ci/blob/master/runlighthouse.js#L104 is looking for a `TRAVIS_PULL_REQUEST_SLUG`.
